CREATE EXTENSION IF NOT EXISTS vector;

CREATE DATABASE authdb;
CREATE DATABASE orderdb;
CREATE DATABASE paymentdb;
CREATE DATABASE shippingdb;
CREATE DATABASE notificationdb;
CREATE DATABASE analyticsdb;
CREATE DATABASE vectordb;
